# Generated by Django 5.0.3 on 2024-03-24 17:24

import django.core.validators
import django.db.models.deletion
import oauth.endpoint.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=oauth.endpoint.services.get_path_upload_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), oauth.endpoint.services.validate_size_image])),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Группа')),
                ('vk', models.CharField(blank=True, max_length=10, null=True, verbose_name='ВКонтакте')),
                ('tg', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telegram')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('gmail', models.EmailField(blank=True, max_length=255, unique=True, verbose_name='Электронная почта Google')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth.role', verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='oauth.authuser')),
            ],
        ),
    ]
